apiVersion: v1
kind: PersistentVolume
metadata:
  name: strapi-volume
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/strapi-store
    server: nfs.default.com
  persistentVolumeReclaimPolicy: Retain