version: "3"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
  backend:
    image: iac-registry.pgsm.hu/peter7nagy/changepoint/backend
    container_name: backend
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example